import { WebSocket } from 'ws'
import { gameCommands, manageGameEvents } from '../../utils/constants.js'
import { sendResponse } from './utils.js'

export function sendCreateGameResponse(ws: WebSocket, idGame: string | number, idPlayer: string | number) {
  sendResponse(ws, manageGameEvents.createGame, {
    idGame,
    idPlayer,
  })
}
export function sendTurnInfo(ws: WebSocket, currentPlayer: string | number) {
  sendResponse(ws, gameCommands.turn, {
    currentPlayer,
  })
}
/*
{
    type: "create_game", //send for both players in the room, after they are connected to the room
    data:
        {
            idGame: <number | string>,  
            idPlayer: <number | string>, generated by server id for player in the game session, not enemy (unique id for every player) 
        },
    id: 0,
}
*/
